name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: cc288af760054fa489574bd8e22d05aa8fa01e5c

      - name: Configure & build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: release
          buildPreset: release
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Upload plugin DLL
        uses: actions/upload-artifact@v4
        with:
          name: DynamicStealingBlockingSKSE
          path: build/**/DynamicStealingBlockingSKSE.dll
